language: php

sudo: false

php:
    - 7.1
    - 7.2

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y realpath shellcheck
    - phpenv config-rm xdebug.ini

script:
    - tests/tests.sh
    - shellcheck xdebug
    - shellcheck tests/tests.sh
